"""``vorqd.opsig`` against the vectors the contracts themselves produced.

``tests/vectors/signing-v3.json`` is generated by
``vorq-evm-contracts/test/Vectors.t.sol``: every case is signed over the digest
derived from its own published payload and is then handed to the deployed
contract and accepted. It is the authority here — every expected value below is
**read out of the file**, never restated, so a change to the contracts' types or
domains fails these tests rather than agreeing with a stale copy.

The strongest assertions are the ones that recover the file's own signature
through this SDK's encoding. The private keys are deliberately absent from the
file, so recovery — not re-signing — is what proves that direction.
"""

from __future__ import annotations

import inspect
import json
from dataclasses import replace

import pytest
from eth_account import Account
from eth_utils import keccak

from vorqd import opsig
from vorqd._crypto import SESSION_TYPES, WalletSigner, vorq_domain
from vorqd.escrow import RELEASE_TYPES, release_domain
from vorqd.money import format_usd
from vorqd.opsig import OpSigner
from vorqd.types import ChainContext

from .vectors import ADDRESSES, CASES, DOMAINS, VECTORS, coerce, local_types, message, typed_data

#: The artifacts this daemon signs. The file also carries the client's half
#: (Order, Cancel, the payment authorization); those are the client SDK's to check.
OP_CASES = [
    "claim",
    "settle",
    "fail",
    "set-identity",
    "set-identity-empty-evidence",
    "request-capacity",
]
ASK_CASES = ["ask-snapshot", "ask-snapshot-empty"]
#: Every case this repo signs, including the two artifacts no contract verifies.
SIGNED_CASES = OP_CASES + ASK_CASES + ["release", "session"]


#: The payment token's decimals: the vectors' rates are atomic at USDC's six.
DECIMALS = 6


def chain_context() -> ChainContext:
    """The deployment the vectors were generated against."""
    return ChainContext(
        chain_id=VECTORS["chain_id"],
        job_registry=ADDRESSES["job_registry"],
        provider_registry=ADDRESSES["provider_registry"],
        ask_registry=ADDRESSES["ask_registry"],
        usdc=ADDRESSES["payment_token"],
        decimals=DECIMALS,
    )


def primary_of(name: str) -> str:
    return CASES[name]["typed_data"]["primaryType"]


def our_typed_data(name: str) -> dict:
    """The case rebuilt through :mod:`vorqd.opsig` rather than read from the file."""
    return opsig.typed_data(primary_of(name), message(name), chain_context())


# --------------------------------------------------------------------------- #
# The type tables are the contracts', not a plan's
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize("name", OP_CASES + ASK_CASES)
def test_our_type_table_is_the_one_the_contract_verifies(name: str) -> None:
    """Direct list equality against the published table.

    A member renamed, retyped or reordered changes the typehash, which changes
    the digest, which makes the signature recover a different address — and the
    contract refuses it with no error that names the cause. The published table
    is the one a signature the contract ACCEPTED was built from, so agreeing with
    it is the whole check; there is no derived type string to compare.
    """
    assert opsig.SIGNED_TYPES[primary_of(name)] == local_types(name)


def test_the_release_type_table_matches_the_vector() -> None:
    """No contract verifies a Release, so this file and the coordinator are the
    only two places it exists. That is exactly why it needs a vector."""
    assert RELEASE_TYPES == local_types("release")


def test_the_session_type_table_matches_the_vector() -> None:
    assert SESSION_TYPES == local_types("session")


def test_no_op_type_carries_a_cid() -> None:
    """``Settle`` attests the delivered count and nothing about which bytes produced it."""
    for members in opsig.OP_TYPES.values():
        for struct in members.values():
            assert not any("cid" in member["name"].lower() for member in struct)


# --------------------------------------------------------------------------- #
# Digests and signatures, case by case
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize("name", OP_CASES + ASK_CASES)
def test_digest_matches_the_vector(name: str) -> None:
    assert opsig.digest(our_typed_data(name)) == CASES[name]["digest"]


@pytest.mark.parametrize("name", SIGNED_CASES)
def test_the_files_own_payload_hashes_to_its_recorded_digest(name: str) -> None:
    """The file is self-consistent under this language's encoder.

    Independent of :mod:`vorqd.opsig`: it hands ``typed_data`` straight to
    ``eth_account`` and checks the recorded digest and signer. A consumer in any
    language can repeat exactly this.
    """
    assert opsig.digest(typed_data(name)) == CASES[name]["digest"]
    assert opsig.recover(typed_data(name), CASES[name]["signature"]) == CASES[name]["signer"]


@pytest.mark.parametrize("name", OP_CASES + ASK_CASES)
def test_the_contract_signature_recovers_over_our_typed_data(name: str) -> None:
    """The vector's own signature recovers its signer through *our* encoding.

    Stronger than comparing digests: this re-derives the domain separator and the
    struct hash from the type list in :mod:`vorqd.opsig` and proves the signature
    the deployed contract accepted was made over exactly those bytes.
    """
    assert opsig.recover(our_typed_data(name), CASES[name]["signature"]) == CASES[name]["signer"]


@pytest.mark.parametrize("name", OP_CASES + ASK_CASES)
def test_domain_is_the_one_the_vector_records(name: str) -> None:
    assert opsig.domain_for(primary_of(name), chain_context()) == CASES[name]["typed_data"]["domain"]


def test_the_release_domain_is_the_one_the_vector_records() -> None:
    assert release_domain(VECTORS["chain_id"]) == CASES["release"]["typed_data"]["domain"]


def test_the_session_domain_is_the_one_the_vector_records() -> None:
    """Bound to the deployment's chain, like every other artifact, because a
    browser wallet only signs a domain on the chain it is switched to. Version
    "1" and no verifyingContract keep it out of every contract's namespace."""
    domain = CASES["session"]["typed_data"]["domain"]
    assert vorq_domain(VECTORS["chain_id"]) == domain
    assert domain["chainId"] == VECTORS["chain_id"]
    assert "verifyingContract" not in domain


# --------------------------------------------------------------------------- #
# Round trip: what OpSigner produces
# --------------------------------------------------------------------------- #


@pytest.fixture
def op_signer() -> OpSigner:
    return OpSigner(WalletSigner.generate())


def signed_for(name: str, signer: OpSigner) -> str:
    """Sign the vector case's fields through the public ``sign_*`` method."""
    ctx, msg, primary = chain_context(), message(name), primary_of(name)
    if primary == "Claim":
        return signer.sign_claim(msg["jobId"], msg["issuedAt"], ctx)
    if primary == "Settle":
        return signer.sign_settle(msg["jobId"], msg["completionTok"], msg["issuedAt"], ctx)
    if primary == "Fail":
        return signer.sign_fail(msg["jobId"], msg["issuedAt"], ctx)
    if primary == "SetIdentity":
        return signer.sign_set_identity(msg["boxKey"], msg["evidence"], msg["issuedAt"], ctx)
    return signer.sign_request_capacity(msg["n"], msg["issuedAt"], ctx)


@pytest.mark.parametrize("name", OP_CASES)
def test_sign_round_trips_over_the_vector_typed_data(name: str, op_signer: OpSigner) -> None:
    """Our signature recovers our own address **over the vector's typed data**.

    That is what ties the ``sign_*`` methods to the digests above: a method that
    signed some other domain or some other member order would recover a
    different address here.
    """
    signature = signed_for(name, op_signer)
    assert opsig.recover(typed_data(name), signature) == op_signer.address
    assert Account._recover_hash(CASES[name]["digest"], signature=signature) == op_signer.address


@pytest.mark.parametrize("name", ASK_CASES)
def test_the_ask_snapshot_round_trips_through_its_signer(name: str, op_signer: OpSigner) -> None:
    """The one assertion the chain makes: ``idOf(ecrecover(...)) == providerId``.

    ``ask_snapshot_message`` takes the wire body itself, so the snapshot signed
    and the snapshot pushed cannot come apart.
    """
    signature = op_signer.sign_ask_snapshot(wire_snapshot(name), chain_context())
    assert opsig.recover(typed_data(name), signature) == op_signer.address


def wire_snapshot(name: str) -> dict:
    """The vector's snapshot in the shape ``PUT /evm/asks`` carries it.

    The rates as USD decimal strings, every other member a JSON integer.
    """
    msg = message(name)
    return {
        "provider_id": int(msg["providerId"]),
        "signed_at": int(msg["signedAt"]),
        "quotes": [
            {
                "model_id": int(q["modelId"]),
                "sla": int(q["sla"]),
                "rate_in": format_usd(int(q["rateIn"]), DECIMALS),
                "rate_out": format_usd(int(q["rateOut"]), DECIMALS),
            }
            for q in msg["quotes"]
        ],
    }


@pytest.mark.parametrize("name", ASK_CASES)
def test_the_wire_snapshot_signs_to_the_vector_digest(name: str) -> None:
    """The wire body in, the digest out — the snapshot pushed is the one signed."""
    data = opsig.typed_data(
        "AskSnapshot", opsig.ask_snapshot_message(wire_snapshot(name), DECIMALS), chain_context()
    )
    assert opsig.digest(data) == CASES[name]["digest"]


def test_a_job_id_hex_string_signs_the_same_as_bytes(op_signer: OpSigner) -> None:
    raw = CASES["claim"]["typed_data"]["message"]
    as_hex = op_signer.sign_claim(raw["jobId"], raw["issuedAt"], chain_context())
    assert opsig.recover(typed_data("claim"), as_hex) == op_signer.address


def test_claim_and_fail_have_identical_members_but_different_digests() -> None:
    """Only the type NAME separates them, which is exactly what makes this dangerous.

    No table-equality assertion can catch a signer that reuses one type for the
    other: the member lists are identical. Only the digests differ.
    """
    assert message("claim") == message("fail")
    assert CASES["claim"]["digest"] != CASES["fail"]["digest"]
    assert opsig.digest(our_typed_data("claim")) != opsig.digest(our_typed_data("fail"))


# --------------------------------------------------------------------------- #
# The three domains, and what keeps them apart
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize(
    ("name", "wrong_field"),
    [("request-capacity", "job_registry"), ("ask-snapshot", "job_registry"), ("claim", "ask_registry")],
)
def test_a_wrong_verifying_contract_recovers_a_stranger(name: str, wrong_field: str) -> None:
    """The failure mode this whole file exists for, made loud.

    The three VORQ domains share a name, a version and a chain id and differ only
    in ``verifyingContract``. A wrong one produces a **silently invalid**
    signature rather than an error: ``setAsks`` skips the entry, the registries
    refuse it, and nothing anywhere says why. So the assertion is not that
    something raises — it is that the recovered address is a stranger.
    """
    ctx = chain_context()
    field = opsig.SIGNED_REGISTRY[primary_of(name)]
    confused = replace(ctx, **{field: getattr(ctx, wrong_field)})

    wrong = opsig.typed_data(primary_of(name), message(name), confused)
    assert opsig.digest(wrong) != CASES[name]["digest"]

    stranger = opsig.recover(wrong, CASES[name]["signature"])
    assert stranger != CASES[name]["signer"]


def test_the_three_domains_differ_at_all() -> None:
    """Without this the confusion cases above would prove nothing."""
    separators = {DOMAINS[k]["separator"] for k in ("job_registry", "provider_registry", "ask_registry")}
    assert len(separators) == 3

    ctx = chain_context()
    for primary, expected in {
        "Claim": ctx.job_registry,
        "Settle": ctx.job_registry,
        "Fail": ctx.job_registry,
        "SetIdentity": ctx.provider_registry,
        "RequestCapacity": ctx.provider_registry,
        "AskSnapshot": ctx.ask_registry,
    }.items():
        assert opsig.domain_for(primary, ctx)["verifyingContract"] == expected


def test_the_off_chain_domains_name_no_contract() -> None:
    """Release and VorqSession have no verifying contract at all — three domain
    members, not four — and the file says so with a null separator rather than a
    zero word a consumer might compare against."""
    for key in ("escrow", "session"):
        assert DOMAINS[key]["separator"] is None
        assert "verifyingContract" not in DOMAINS[key]["domain"]


def test_the_domain_is_never_a_parameter() -> None:
    """No ``sign_*`` takes a domain, an address or a type string.

    The defence is structural: a caller that cannot state a domain cannot state
    the wrong one.
    """
    for name, method in inspect.getmembers(OpSigner, inspect.isfunction):
        if not name.startswith("sign_"):
            continue
        params = set(inspect.signature(method).parameters)
        assert not params & {"domain", "verifying_contract", "contract", "types", "primary_type"}
        assert "ctx" in params


# --------------------------------------------------------------------------- #
# What is deliberately absent
# --------------------------------------------------------------------------- #


def test_settle_takes_no_result_cid() -> None:
    """The daemon does not know the name and does not sign one."""
    params = inspect.signature(OpSigner.sign_settle).parameters
    assert list(params) == ["self", "job_id", "completion_tok", "issued_at", "ctx"]
    assert not any("cid" in p.lower() for p in params)


def test_there_is_no_reclaim_op() -> None:
    """``reclaim`` is permissionless and unsigned; an SDK signing path would lie."""
    assert not hasattr(OpSigner, "sign_reclaim")
    assert "Reclaim" not in opsig.OP_TYPES
    assert "reclaim" not in set(opsig.OP_NAMES.values())


def test_the_five_ops_are_the_five_the_node_relays() -> None:
    assert set(opsig.OP_NAMES.values()) == {
        "claim",
        "settle",
        "fail",
        "set_identity",
        "request_capacity",
    }
    assert set(opsig.OP_TYPES) == set(opsig.OP_NAMES) == set(opsig.OP_REGISTRY)


def test_the_ask_snapshot_is_not_an_op() -> None:
    """It is signed here, and it does **not** go through ``POST /evm/ops``.

    A whole book replaces a whole book at ``PUT /evm/asks``; the ops door relays
    one act at a time. Keeping ``AskSnapshot`` out of ``OP_NAMES`` is what stops
    a caller pushing it to the wrong door and getting a `400` for a reason that
    names nothing.
    """
    assert "AskSnapshot" not in opsig.OP_NAMES
    assert "AskSnapshot" not in opsig.OP_TYPES
    assert "AskSnapshot" in opsig.SIGNED_TYPES
    assert opsig.SIGNED_REGISTRY["AskSnapshot"] == "ask_registry"
    assert set(opsig.OP_TYPES) < set(opsig.SIGNED_TYPES)


def test_a_withdrawal_rides_as_rate_out_zero_and_is_signed_like_any_other_quote() -> None:
    """A withdrawn slot is a quote, not an omission (``AskRegistry.setAsks``).

    On chain the write is an upsert: a slot the snapshot omits keeps its previous
    price forever. Only ``rateOut == 0`` deletes one — so the withdrawal has to be
    inside the signed struct. The vector carries one, and the contracts' own
    acceptance test reads the emptied slot back through ``getQuote``.
    """
    quotes = message("ask-snapshot")["quotes"]
    assert any(q["rateOut"] == 0 for q in quotes)

    without = {**wire_snapshot("ask-snapshot"), "quotes": wire_snapshot("ask-snapshot")["quotes"][:1]}
    ctx = chain_context()
    assert opsig.digest(
        opsig.typed_data("AskSnapshot", opsig.ask_snapshot_message(without, DECIMALS), ctx)
    ) != CASES["ask-snapshot"]["digest"]


def test_an_empty_snapshot_is_signable() -> None:
    """The all-withdrawn book a drain pushes still hashes: ``keccak256("")`` of no
    element hashes is a real value, not a zero word."""
    assert message("ask-snapshot-empty")["quotes"] == []
    assert opsig.digest(our_typed_data("ask-snapshot-empty")) == CASES["ask-snapshot-empty"]["digest"]


def test_the_snapshot_is_signed_from_the_wire_body_itself() -> None:
    """The wire body survives a JSON round trip, and signing carries the full widths."""
    snap = wire_snapshot("ask-snapshot")
    assert opsig.ask_snapshot_message(snap, DECIMALS) == opsig.ask_snapshot_message(
        json.loads(json.dumps(snap)), DECIMALS)

    huge = {
        "provider_id": 7,
        "signed_at": 2**64 - 1,
        "quotes": [
            {
                "model_id": 1,
                "sla": 3600,
                "rate_in": format_usd(2**128 - 1, DECIMALS),
                "rate_out": "0.000001",
            }
        ],
    }
    assert opsig.ask_snapshot_message(huge, DECIMALS)["signedAt"] == 2**64 - 1
    assert opsig.ask_snapshot_message(huge, DECIMALS)["quotes"][0]["rateIn"] == 2**128 - 1
    assert opsig.ask_snapshot_message(huge, DECIMALS)["quotes"][0]["rateOut"] == 1


#: The secp256k1 group order. A canonical signature carries `s <= N // 2`; the
#: twin at `N - s` recovers the same address, which is what makes signature bytes
#: unusable as an identity.
SECP256K1_N = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141


@pytest.mark.parametrize("name", OP_CASES)
def test_every_signature_this_daemon_produces_is_canonical(name: str, op_signer: OpSigner) -> None:
    """Low-`s`, and `v` in {27, 28}, on every op the daemon authorises.

    **The registries do not enforce this and never will.** `JobRegistry._recover`
    and `ProviderRegistry._recover` call bare `ecrecover` with no canonical-`s`
    bound, so the high-`s` twin `(r, N - s, 55 - v)` of any signature below
    recovers the same operator address and is accepted just as readily. That is
    deliberate: replay is stopped by the job state machine and by the monotonic
    `issuedAt` floors, never by signature bytes.

    The rule it leaves on this side is one line — **a signature is never an
    identifier** — and this is what keeps it true rather than incidental to
    whichever `eth-account` is installed.
    """
    raw = bytes.fromhex(signed_for(name, op_signer)[2:])
    assert len(raw) == 65
    s = int.from_bytes(raw[32:64], "big")
    assert 0 < s <= SECP256K1_N // 2, f"{name} carries a high-s signature"
    assert raw[64] in (27, 28), f"{name} carries v={raw[64]}, which recovers address(0)"


def test_the_ask_snapshot_signature_is_canonical_too(op_signer: OpSigner) -> None:
    """The third domain, held to the same rule as the five ops.

    Signed here rather than on `WalletSigner` (the module docstring says why), so
    it is the one signature that could drift away from the others without any of
    the parametrized cases above noticing.
    """
    # `wire_snapshot("ask-snapshot")` returns the vector's own book in wire shape;
    # a hand-built one would work too, but this keeps one source for the fields.
    raw = bytes.fromhex(
        op_signer.sign_ask_snapshot(wire_snapshot("ask-snapshot"), chain_context())[2:]
    )
    assert len(raw) == 65
    assert 0 < int.from_bytes(raw[32:64], "big") <= SECP256K1_N // 2
    assert raw[64] in (27, 28)


def test_the_high_s_twin_recovers_the_same_operator(op_signer: OpSigner) -> None:
    """Why the rule above is a rule, demonstrated once.

    Different bytes, same digest, same recovered address — so a node that
    deduplicated relayed ops on the signature would relay the same claim twice
    and pay gas for the second one.
    """
    raw = bytes.fromhex(signed_for("claim", op_signer)[2:])
    twin = (
        raw[0:32]
        + (SECP256K1_N - int.from_bytes(raw[32:64], "big")).to_bytes(32, "big")
        # 27 <-> 28. Not `v ^ 1`: that is the {0, 1} recovery-id convention, and
        # it takes 27 to 26, which `eth-account` refuses outright.
        + bytes([55 - raw[64]])
    )

    assert twin != raw
    assert opsig.recover(our_typed_data("claim"), "0x" + twin.hex()) == op_signer.address


# --------------------------------------------------------------------------- #
# Refusals
# --------------------------------------------------------------------------- #


def test_an_unknown_op_has_no_domain() -> None:
    with pytest.raises(ValueError, match="Reclaim"):
        opsig.domain_for("Reclaim", chain_context())


def test_a_short_job_id_is_refused_rather_than_padded(op_signer: OpSigner) -> None:
    with pytest.raises(ValueError, match="32 bytes"):
        op_signer.sign_claim("0xdeadbeef", 1800000000, chain_context())


def test_absent_evidence_signs_as_empty_bytes(op_signer: OpSigner) -> None:
    """``None`` and ``0x`` are the same op — and both hash, never zero-pad."""
    ctx = chain_context()
    msg = message("set-identity-empty-evidence")
    assert msg["evidence"] == b""
    assert op_signer.sign_set_identity(msg["boxKey"], None, msg["issuedAt"], ctx) == (
        op_signer.sign_set_identity(msg["boxKey"], b"", msg["issuedAt"], ctx)
    )
    assert CASES["set-identity-empty-evidence"]["extra"]["evidence_hash"] == "0x" + keccak(b"").hex()


def test_the_coercion_is_driven_by_the_declared_type(op_signer: OpSigner) -> None:
    """Sanity on the loader itself: widths that a JSON double would round come back
    as exact integers, and byte members as bytes."""
    assert isinstance(message("claim")["jobId"], bytes)
    assert isinstance(message("set-identity")["evidence"], bytes)
    assert all(isinstance(q["rateIn"], int) for q in message("ask-snapshot")["quotes"])
    assert coerce({"T": [{"name": "v", "type": "uint128"}]}, "T", {"v": "340282366920938463463374607431768211455"})[
        "v"
    ] == 2**128 - 1
