"""Loader for ``tests/vectors/signing-v3.json``, the cross-language signing vectors.

The file is generated by ``vorq-evm-contracts/test/Vectors.t.sol``, where every
case is signed over the digest Foundry derives from the case's own published
payload and is then handed to the deployed contract and accepted. It is
therefore the authority: nothing here restates an expected value.

Each case carries a **standard EIP-712 payload** under ``typed_data`` —
``{types, primaryType, domain, message}`` — which is exactly the object
:func:`eth_account.messages.encode_typed_data` takes. So a test can hand the
file's own bytes to the encoder rather than rebuilding them, and an SDK's local
type table is checked by direct list equality against ``typed_data.types``.

The only transformation needed is :func:`coerce`, and it exists for one reason:
JSON has one number type. ``uint128``/``uint256`` are carried as decimal strings
because a 256-bit value does not survive a double, and ``bytes``/``bytes32`` as
``0x`` hex. The declared type in ``types`` says which is which, so the decoding
is driven by the file rather than by a hand-written field list that could drift.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

VECTORS: dict[str, Any] = json.loads(
    (Path(__file__).parent / "vectors" / "signing-v3.json").read_text()
)

CASES: dict[str, dict[str, Any]] = {case["name"]: case for case in VECTORS["cases"]}
ADDRESSES: dict[str, str] = VECTORS["addresses"]
DOMAINS: dict[str, Any] = VECTORS["domains"]


def coerce(types: dict[str, list[dict[str, str]]], primary: str, message: dict) -> dict:
    """``message`` with each member decoded according to its declared EIP-712 type."""
    out: dict[str, Any] = {}
    for member in types[primary]:
        name, declared, value = member["name"], member["type"], message[member["name"]]
        if declared.endswith("[]"):
            out[name] = [coerce(types, declared[:-2], element) for element in value]
        elif declared in types:
            out[name] = coerce(types, declared, value)
        elif declared.startswith("bytes"):
            out[name] = bytes.fromhex(value.removeprefix("0x"))
        elif declared.startswith("uint") and isinstance(value, str):
            out[name] = int(value)
        else:
            out[name] = value
    return out


def typed_data(name: str) -> dict[str, Any]:
    """A case's payload, ready for ``encode_typed_data(full_message=...)``."""
    case = CASES[name]
    payload = dict(case["typed_data"])
    payload["message"] = coerce(payload["types"], payload["primaryType"], payload["message"])
    return payload


def message(name: str) -> dict[str, Any]:
    """Just the decoded message members of a case."""
    return typed_data(name)["message"]


def local_types(name: str) -> dict[str, list[dict[str, str]]]:
    """A case's ``types`` block without ``EIP712Domain``.

    That is the shape an SDK declares: the domain's own type list is boilerplate
    every EIP-712 encoder already knows, so no SDK writes it down.
    """
    return {k: v for k, v in CASES[name]["typed_data"]["types"].items() if k != "EIP712Domain"}
